### ISSUE TITLE
Couldn't find an email on your account 

### ISSUE THREAD

**Issue by ms10398** [faustinoaq/faustinoaq.github.io#1]
Hello @faustinoaq ,

I wanted to share with you about an amazing community but couldn't find an email or some means of contact so thought the best way to ping you up would be issue tracker of your personal webpage. :slightly_smiling_face: 

Thanks!

**Comment by faustinoaq** [comment]
Hi @ms10398 I haven't shared my email to avoid spam, although I'm pretty sure my email is leaked in some hacker database on Internet :sweat_smile: 

You can send me a private message using Gitter :point_right: https://gitter.im/faustinoaq
